name: Testing WP-GitHub-Card
on:
  push:
    branches:
        - master
  pull_request:
  repository_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Setup WP
        run: bash ./bin/install-wp-tests.sh wordpress_test root '' localhost 5.8
        shell: bash
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: phpunit
      - name: Run PHPUnit
        run: phpunit
